### ISSUE TITLE
ClusterfuzzLite does not check out submodules

### ISSUE THREAD

**Issue by Deniskore** [google/clusterfuzzlite#107]
I tried to add a custom step to [fuzzing configuration](https://github.com/neonlabsorg/proxy-model.py/pull/881) to check out submodule, but it didn't help.

```yaml
  - name: Checkout source
    uses: actions/checkout@v2
    id: checkout
    with:
      path: storage/proxy-model.py
      submodules: true
```
I got an error after all the fuzzers were built:
```
RuntimeError: Executing command "git rev-parse HEAD" failed with error: fatal: detected dubious ownership in repository at '/github/workspace/storage/proxy-model.py'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/storage/proxy-model.py
```
